# Generated by Django 3.2.1 on 2021-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financialreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin', models.FileField(upload_to='pdfreports')),
                ('fina', models.FileField(upload_to='pdfreports')),
                ('year', models.CharField(max_length=50)),
                ('yearf', models.CharField(max_length=50)),
                ('yeara', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('amount', models.BigIntegerField()),
            ],
        ),
    ]
