# Generated by Django 3.2.1 on 2021-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=7)),
                ('availability', models.CharField(choices=[('WD', 'weekdays'), ('WE', 'weekends'), ('B', 'both'), ('V', 'varies')], max_length=2)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.BigIntegerField()),
                ('role', models.CharField(max_length=400)),
                ('address', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
