# Generated by Django 3.2.1 on 2021-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=3)),
                ('month', models.CharField(max_length=15)),
                ('specialday', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Eventform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True)),
                ('Age', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Category', models.CharField(choices=[('F', 'Festival'), ('B', 'Birthday'), ('A', 'Anniversary')], max_length=1, null=True)),
                ('People', models.IntegerField()),
                ('Event_Date', models.DateTimeField()),
                ('Event_Celebrations', models.CharField(choices=[('2', 'Sri Alluri Yuvajana Seva Sangam'), ('3', 'Mr Mani'), ('4', 'Childrens Home')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='eventphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='pictures')),
                ('info', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
