# Generated by Django 3.2.1 on 2021-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodregdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('food1', models.CharField(choices=[('M', 'veg'), ('F', 'nonveg'), ('U', 'both')], max_length=1, null=True)),
                ('food2', models.CharField(choices=[('FRO', 'frozen'), ('FRE', 'fresh'), ('COOK', 'cooked')], max_length=4, null=True)),
                ('fooddate', models.DateTimeField()),
                ('foodQuantity', models.IntegerField(null=True)),
                ('foodpack', models.CharField(choices=[('L', 'loose'), ('P', 'packed')], max_length=1, null=True)),
                ('locality', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
            ],
        ),
    ]
